name: Build PR Documentation

on:
  pull_request:
    paths:
      - "notebooks/**"
      - ".github/workflows/build_pr_documentation.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@main
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: cookbook
      package_name: cookbook
      path_to_docs: cookbook/notebooks/
      additional_args: --not_python_module
      languages: en zh-CN ko tr fr
      convert_notebooks: true
